#!/usr/bin/env bash

# Function to get DNS information for a subdomain
dns_config () {
    script=$(dig "$2"."$1" +short)
    record_type=$(dig "$2"."$1" +noall +answer | awk '{print $4}')
    echo "$2 $script" | awk -v rt="$record_type" '{print "The subdomain " $1 " is a " rt " record and points to " $2}'
}

# Check the number of arguments and call dns_config accordingly
if [ "$#" -eq 1 ]; then
  dns_config "$1" "www"
  dns_config "$1" "lb-01"
  dns_config "$1" "web-01"
  dns_config "$1" "web-02"
elif [ "$#" -eq 2 ]; then
  dns_config "$1" "$2"
else
  echo "Usage: $0 domain [subdomain]"
fi

