#!/usr/bin/env bash

""" Function to get DNS information for a subdomain """
dns_config () {
    domain="$1"
    subdomain="$2"
    record=$(dig "$subdomain.$domain" +short)
    record_type=$(dig "$subdomain.$domain" +noall +answer | awk '{print $4}')
    echo "$subdomain $record" | awk -v rt="$record_type" '{print "The subdomain " $1 " is a " rt " record and points to " $2}'
}

# Main script logic
if [ "$#" -eq 1 ]; then
    domain="$1"
    dns_config "$domain" "www"
    dns_config "$domain" "lb-01"
    dns_config "$domain" "web-01"
    dns_config "$domain" "web-02"
elif [ "$#" -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    dns_config "$domain" "$subdomain"
else
    echo "Usage: $0 domain [subdomain]"
fi
