#!/usr/bin/env bash
# Installs nginx server

# Update package list and install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Create the HTML file to serve
echo "Hello World!" | sudo tee /var/www/html/index.html

# Modify the default Nginx server block configuration to serve the custom HTML
sudo sed -i 's|root /var/www/html;|root /var/www/html; index index.html;|' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx start

# Ensure Nginx is listening on port 80

sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

sudo sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/g' /etc/nginx/sites-available/default

sudo nginx -s reload

# Enable Nginx to start on boot
sudo update-rc.d nginx defaults
