#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
sudo apt update
sudo apt install nginx -y

#Add custom HTTP header to Nginx config

sudo sed -i '/server {/a \\tadd_header X-Served-By \$hostname;' /etc/nginx/sites-available/default

#Test and restart Nginx

sudo nginx -t && sudo systemctl restart nginx
