#!/usr/bin/env bash
# Enable UFW
sudo ufw enable

# Set default policies to deny all incoming traffic
sudo ufw default deny incoming

# Allow incoming traffic on TCP port 22 (SSH)
sudo ufw allow ssh

# Allow incoming traffic on TCP port 443 (HTTPS SSL)
sudo ufw allow https

# Allow incoming traffic on TCP port 80 (HTTP)
sudo ufw allow http

# Reload UFW to apply changes
sudo ufw reload
