#!/usr/bin/env bash
# UFW configuration file

*filter
:ufw-before-input - [0:0]
:ufw-before-output - [0:0]
:ufw-before-forward - [0:0]
:ufw-not-local - [0:0]
# Allow all loopback traffic
-A ufw-before-input -i lo -j ACCEPT
-A ufw-before-output -o lo -j ACCEPT

# Redirect port 8080/TCP to port 80/TCP
-A PREROUTING -t nat -p tcp --dport 8080 -j REDIRECT --to-port 80

# Allow incoming traffic on TCP port 22 (SSH)
-A ufw-before-input -p tcp --dport 22 -j ACCEPT

# Allow incoming traffic on TCP port 443 (HTTPS SSL)
-A ufw-before-input -p tcp --dport 443 -j ACCEPT

# Allow incoming traffic on TCP port 80 (HTTP)
-A ufw-before-input -p tcp --dport 80 -j ACCEPT
